package co.sublimetech.lideres.core.presentation

object Constants {

    // BLOCK 1 FORM DETAILS
    const val FORM_NUMBER = "form_number"
    const val FORM_DATE = "form_date"
    const val FORM_OFFICE = "form_office"

    // BLOCK 2 FORM DATE
    const val FORM_FILL_DATE = "form_fill_date"
    const val FORM_COUNTRY = "form_country"
    const val FORM_DEPARTMENT = "form_department"
    const val FORM_CITY = "form_city"

    // BLOCK 3 APPLICANT PERSONAL DATA
    const val APPLICANT_FIRST_NAME = "applicant_first_name"
    const val APPLICANT_SECOND_NAME = "applicant_second_name"
    const val APPLICANT_FIRST_LAST_NAME = "applicant_first_last_name"
    const val APPLICANT_SECOND_LAST_NAME = "applicant_second_last_name"
    const val APPLICANT_IDENTIFYING_NAME = "applicant_identifying_name"
    const val APPLICANT_ID_TYPE = "applicant_id_type"
    const val APPLICANT_ID_NUMBER = "applicant_id_number"
    const val APPLICANT_ID_EXPEDITION_DATE = "applicant_id_expedition_date"
    const val APPLICANT_COUNTRY_OF_BIRTH = "applicant_country_of_birth"
    const val APPLICANT_DEPARTMENT_OF_BIRTH = "applicant_department_of_birth"
    const val APPLICANT_CITY_OF_BIRTH = "applicant_city_of_birth"
    const val APPLICANT_DATE_OF_BIRTH = "applicant_date_of_birth"
    const val APPLICANT_ADDRESS_COUNTRY = "applicant_country_of_birth"
    const val APPLICANT_ADDRESS_DEPARTMENT = "applicant_address_department"
    const val APPLICANT_ADDRESS_CITY= "applicant_address_city"
    const val APPLICANT_ADDRESS_DISTRICT= "applicant_address_district"
    const val APPLICANT_ADDRESS_SETTLEMENT = "applicant_address_settlement"
    const val APPLICANT_ADDRESS_NEIGHBORHOOD = "applicant_address_neighborhood"
    const val APPLICANT_ADDRESS_ZONE = "applicant_address_zone"
    const val APPLICANT_ADDRESS= "applicant_address"
    const val APPLICANT_ADDRESS_DETAILS= "applicant_address_details"
    const val APPLICANT_PHONE_NUMBER_1= "applicant_phone_number_1"
    const val APPLICANT_PHONE_NUMBER_2= "applicant_phone_number_2"
    const val APPLICANT_LANDLINE= "applicant_landline"
    const val APPLICANT_EMAIL= "applicant_email"
    const val APPLICANT_NOTIFICATION_APPROVAL= "applicant_notification_approval"
    const val APPLICANT_NOTIFICATION_COUNTRY= "applicant_notification_country"
    const val APPLICANT_NOTIFICATION_DEPARTMENT= "applicant_notification_department"
    const val APPLICANT_NOTIFICATION_CITY= "applicant_notification_city"
    const val APPLICANT_NOTIFICATION_ADDRESS= "applicant_notification_address"

    // BLOCK 4 THIRD PARTY REQUEST DATA
    const val THIRD_PARTY_NAMES_AND_LASTNAMES = "third_party_names_and_lastnames"
    const val THIRD_PARTY_ADDRESS_COUNTRY = "third_party_address_country"
    const val THIRD_PARTY_ADDRESS_DEPARTMENT = "third_party_address_department"
    const val THIRD_PARTY_ADDRESS_CITY= "third_party_address_city"
    const val THIRD_PARTY_ADDRESS_DISTRICT= "third_party_address_district"
    const val THIRD_PARTY_ADDRESS_SETTLEMENT = "third_party_address_settlement"
    const val THIRD_PARTY_ADDRESS_NEIGHBORHOOD = "third_party_address_neighborhood"
    const val THIRD_PARTY_ADDRESS= "third_party_address"
    const val THIRD_PARTY_ADDRESS_DETAILS= "third_party_address_details"
    const val THIRD_PARTY_PHONE_NUMBER_1= "third_party_phone_number_1"
    const val THIRD_PARTY_PHONE_NUMBER_2= "third_party_phone_number_2"
    const val THIRD_PARTY_LANDLINE= "third_party_landline"
    const val THIRD_PARTY_EMAIL= "third_party_email"
    const val THIRD_PARTY_NOTIFICATION_APPROVAL= "third_party_notification_approval"

    // BLOCK 5 APPLICANT PERSONAL DATA 2
    const val APPLICANT_SEX = "applicant_sex"
    const val APPLICANT_GENDER = "applicant_gender"
    const val APPLICANT_SEXUAL_ORIENTATION = "applicant_sexual_orientation"
    const val APPLICANT_AGE = "applicant_age"
    const val APPLICANT_IDENTIFYING_TRAIT = "applicant_identifying_trait"
    const val APPLICANT_IDENTIFYING_TRAIT_AMOUNT = "applicant_identifying_trait_amount"
    const val APPLICANT_DISABILITY_STATUS = "applicant_disability_status"
    const val APPLICANT_DISABILITY_TYPE = "applicant_disability_type"
    const val APPLICANT_ETHNIC_GROUP_STATUS = "applicant_ethnic_group_status"
    const val APPLICANT_ETHNIC_GROUP_TYPE = "applicant_ethnic_group_type"
    const val APPLICANT_INDIGENOUS_GROUP = "applicant_ethnic_group"
    const val APPLICANT_INDIGENOUS_GROUP_RESERVATION = "applicant_ethnic_group_reservation"
    const val APPLICANT_INDIGENOUS_GROUP_RESERVATION_COMMUNITY = "applicant_ethnic_group_reservation_community"
    const val APPLICANT_INDIGENOUS_GROUP_PARTIAL = "applicant_ethnic_group_partial"
    const val APPLICANT_INDIGENOUS_GROUP_NO_REGISTRY = "applicant_ethnic_group_no_registry"
    const val APPLICANT_AFRICAN_AMERICAN_COMMUNITY = "applicant_ethnic_group_african_american_community"
    const val APPLICANT_ORGANIZATION_MEMBERSHIP_STATUS = "applicant_organization_membership_status"
    const val APPLICANT_ORGANIZATION_TYPE = "applicant_organization_type"
    const val APPLICANT_ORGANIZATION_MEMBERSHIP_OTHER = "applicant_organization_membership_other"
    const val APPLICANT_ORGANIZATION_NAME = "applicant_organization_name"
    const val APPLICANT_ORGANIZATION_LEGAL_REPRESENTATIVE_STATUS = "applicant_legal_representative_status"
    const val APPLICANT_ORGANIZATION_LEGAL_REPRESENTATIVE_NAME = "applicant_legal_representative_name"
    const val APPLICANT_PROVISIONAL_MEASURES_STATUS = "applicant_provisional_measures_status"
    const val APPLICANT_PROVISIONAL_MEASURES_TYPE = "applicant_provisional_measures_type"

    // BLOCK 7 RISK SITUATION DATA
    const val RISK_SITUATION_TYPE = "risk_situation_type"
    const val RISK_SITUATION_OTHER = "risk_situation_other"
    const val RISK_SITUATION_MEANS_TYPE = "risk_situation_means_type"
    const val RISK_SITUATION_MEANS_OTHER = "risk_situation_means_other"

}