package co.sublimetech.lideres.core.presentation

object Constants {

    // BLOCK 1 FORM DETAILS
    const val FORM_NUMBER = "form_number"
    const val FORM_DATE = "form_date"
    const val FORM_OFFICE = "form_office"

    // BLOCK 2 FORM DATE
    const val FORM_FILL_DATE = "form_fill_date"
    const val FORM_COUNTRY = "form_country"
    const val FORM_DEPARTMENT = "form_department"
    const val FORM_CITY = "form_city"

    // BLOCK 3 APPLICANT PERSONAL DATA
    const val APPLICANT_FIRST_NAME = "applicant_first_name"
    const val APPLICANT_SECOND_NAME = "applicant_second_name"
    const val APPLICANT_FIRST_LAST_NAME = "applicant_first_last_name"
    const val APPLICANT_SECOND_LAST_NAME = "applicant_second_last_name"
    const val APPLICANT_IDENTIFYING_NAME = "applicant_identifying_name"
    const val APPLICANT_ID_NATIONAL_ID= "applicant_id_national_id"
    const val APPLICANT_ID_FOREIGN_ID = "applicant_id_foreign_id"
    const val APPLICANT_ID_NUIP = "applicant_id_type_nuip"
    const val APPLICANT_ID_NUMBER = "applicant_id_number"
    const val APPLICANT_ID_EXPEDITION_DATE = "applicant_id_expedition_date"
    const val APPLICANT_COUNTRY_OF_BIRTH = "applicant_country_of_birth"
    const val APPLICANT_DEPARTMENT_OF_BIRTH = "applicant_department_of_birth"
    const val APPLICANT_CITY_OF_BIRTH = "applicant_city_of_birth"
    const val APPLICANT_DATE_OF_BIRTH = "applicant_date_of_birth"
    const val APPLICANT_ADDRESS_COUNTRY = "applicant_country_of_birth"
    const val APPLICANT_ADDRESS_DEPARTMENT = "applicant_address_department"
    const val APPLICANT_ADDRESS_CITY = "applicant_address_city"
    const val APPLICANT_ADDRESS_DISTRICT = "applicant_address_district"
    const val APPLICANT_ADDRESS_SETTLEMENT = "applicant_address_settlement"
    const val APPLICANT_ADDRESS_NEIGHBORHOOD = "applicant_address_neighborhood"
    const val APPLICANT_ADDRESS_ZONE_URBAN = "applicant_address_zone_urban"
    const val APPLICANT_ADDRESS_ZONE_RURAL = "applicant_address_zone_rural"
    const val APPLICANT_ADDRESS = "applicant_address"
    const val APPLICANT_ADDRESS_DETAILS = "applicant_address_details"
    const val APPLICANT_PHONE_NUMBER_1 = "applicant_phone_number_1"
    const val APPLICANT_PHONE_NUMBER_2 = "applicant_phone_number_2"
    const val APPLICANT_LANDLINE = "applicant_landline"
    const val APPLICANT_EMAIL = "applicant_email"
    const val APPLICANT_NOTIFICATION_APPROVAL_POSITIVE = "applicant_notification_approval_positive"
    const val APPLICANT_NOTIFICATION_APPROVAL_NEGATIVE = "applicant_notification_approval_negative"
    const val APPLICANT_NOTIFICATION_COUNTRY = "applicant_notification_country"
    const val APPLICANT_NOTIFICATION_DEPARTMENT = "applicant_notification_department"
    const val APPLICANT_NOTIFICATION_CITY = "applicant_notification_city"
    const val APPLICANT_NOTIFICATION_ADDRESS = "applicant_notification_address"

    // BLOCK 4 THIRD PARTY REQUEST DATA
    const val THIRD_PARTY_NAMES_AND_LASTNAMES = "third_party_names_and_lastnames"
    const val THIRD_PARTY_ADDRESS_COUNTRY = "third_party_address_country"
    const val THIRD_PARTY_ADDRESS_DEPARTMENT = "third_party_address_department"
    const val THIRD_PARTY_ADDRESS_CITY = "third_party_address_city"
    const val THIRD_PARTY_ADDRESS_DISTRICT = "third_party_address_district"
    const val THIRD_PARTY_ADDRESS_SETTLEMENT = "third_party_address_settlement"
    const val THIRD_PARTY_ADDRESS_NEIGHBORHOOD = "third_party_address_neighborhood"
    const val THIRD_PARTY_ADDRESS = "third_party_address"
    const val THIRD_PARTY_ADDRESS_DETAILS = "third_party_address_details"
    const val THIRD_PARTY_PHONE_NUMBER_1 = "third_party_phone_number_1"
    const val THIRD_PARTY_PHONE_NUMBER_2 = "third_party_phone_number_2"
    const val THIRD_PARTY_LANDLINE = "third_party_landline"
    const val THIRD_PARTY_EMAIL = "third_party_email"
    const val THIRD_PARTY_NOTIFICATION_APPROVAL_POSITIVE = "third_party_notification_approval_positive"
    const val THIRD_PARTY_NOTIFICATION_APPROVAL_NEGATIVE = "third_party_notification_approval_negative"

    // BLOCK 5 APPLICANT PERSONAL DATA 2
    const val APPLICANT_SEX_MEN = "applicant_sex_men"
    const val APPLICANT_SEX_WOMEN = "applicant_sex_women"
    const val APPLICANT_SEX_INTERSEXUAL = "applicant_sex_intersexual"
    const val APPLICANT_GENDER_MALE = "applicant_gender_male"
    const val APPLICANT_GENDER_FEMALE = "applicant_gender_female"
    const val APPLICANT_GENDER_TRANSGENDER = "applicant_gender_transgender"
    const val APPLICANT_SEXUAL_ORIENTATION_HETEROSEXUAL = "applicant_sexual_orientation_heterosexual"
    const val APPLICANT_SEXUAL_ORIENTATION_HOMOSEXUAL = "applicant_sexual_orientation_homosexual"
    const val APPLICANT_SEXUAL_ORIENTATION_BISEXUAL = "applicant_sexual_orientation_bisexual"
    const val APPLICANT_AGE_CHILD = "applicant_age_child"
    const val APPLICANT_AGE_TEENAGER = "applicant_age_teenager"
    const val APPLICANT_AGE_YOUNG_ADULT  = "applicant_age_young_adult"
    const val APPLICANT_AGE_ADULT  = "applicant_age_adult"
    const val APPLICANT_AGE_ELDERLY = "applicant_age_elderly"
    const val APPLICANT_IDENTIFYING_TRAIT_FATHER = "applicant_identifying_trait_father"
    const val APPLICANT_IDENTIFYING_TRAIT_MOTHER = "applicant_identifying_trait_mother"
    const val APPLICANT_IDENTIFYING_TRAIT_CARETAKER = "applicant_identifying_trait_caretaker"
    const val APPLICANT_IDENTIFYING_TRAIT_PEOPLE_UNDER_CARE = "applicant_identifying_trait_people_under_care"
    const val APPLICANT_IDENTIFYING_TRAIT_AMOUNT = "applicant_identifying_trait_amount"
    const val APPLICANT_DISABILITY_STATUS_POSITIVE = "applicant_disability_status_positive"
    const val APPLICANT_DISABILITY_STATUS_NEGATIVE = "applicant_disability_status_negative"
    const val APPLICANT_DISABILITY_TYPE_PHYSICAL = "applicant_disability_type_physical"
    const val APPLICANT_DISABILITY_TYPE_HEARING = "applicant_disability_type_hearing"
    const val APPLICANT_DISABILITY_TYPE_VISUAL= "applicant_disability_type_visual"
    const val APPLICANT_DISABILITY_TYPE_BLINDNESS = "applicant_disability_type_blindness"
    const val APPLICANT_DISABILITY_TYPE_MENTAL = "applicant_disability_type_mental"
    const val APPLICANT_DISABILITY_TYPE_INTELLECTUAL = "applicant_disability_type_intellectual"
    const val APPLICANT_DISABILITY_TYPE_LITTLE_PEOPLE = "applicant_disability_type_little_people"
    const val APPLICANT_DISABILITY_TYPE_MULTIPLE = "applicant_disability_type_multiple"
    const val APPLICANT_ETHNIC_GROUP_STATUS_POSITIVE = "applicant_ethnic_group_status_positive"
    const val APPLICANT_ETHNIC_GROUP_STATUS_NEGATIVE = "applicant_ethnic_group_status_negative"
    const val APPLICANT_ETHNIC_GROUP_TYPE_INDIGENOUS = "applicant_ethnic_group_type_indigenous"
    const val APPLICANT_ETHNIC_GROUP_TYPE_NEGRO = "applicant_ethnic_group_type_negro"
    const val APPLICANT_ETHNIC_GROUP_TYPE_AFRICAN_AMERICAN = "applicant_ethnic_group_type_african_american"
    const val APPLICANT_ETHNIC_GROUP_TYPE_SAN_ANDRES = "applicant_ethnic_group_type_indigenous_to_san_andres"
    const val APPLICANT_ETHNIC_GROUP_TYPE_BOLIVAR = "applicant_ethnic_group_type_indigenous_to_bolivar"
    const val APPLICANT_ETHNIC_GROUP_TYPE_GIPSY = "applicant_ethnic_group_type_gipsy"
    const val APPLICANT_INDIGENOUS_GROUP = "applicant_ethnic_group"
    const val APPLICANT_INDIGENOUS_GROUP_RESERVATION = "applicant_ethnic_group_reservation"
    const val APPLICANT_INDIGENOUS_GROUP_RESERVATION_COMMUNITY = "applicant_ethnic_group_reservation_community"
    const val APPLICANT_INDIGENOUS_GROUP_PARTIAL = "applicant_ethnic_group_partial"
    const val APPLICANT_INDIGENOUS_GROUP_NO_REGISTRY = "applicant_ethnic_group_no_registry"
    const val APPLICANT_AFRICAN_AMERICAN_COMMUNITY = "applicant_ethnic_group_african_american_community"
    const val APPLICANT_ORGANIZATION_MEMBERSHIP_STATUS_POSITIVE = "applicant_organization_membership_status_positive"
    const val APPLICANT_ORGANIZATION_MEMBERSHIP_STATUS_NEGATIVE = "applicant_organization_membership_status_negative"
    const val APPLICANT_ORGANIZATION_TYPE_SOCIAL = "applicant_organization_type_social"
    const val APPLICANT_ORGANIZATION_TYPE_GUILD = "applicant_organization_type_guild"
    const val APPLICANT_ORGANIZATION_TYPE_CIVIL = "applicant_organization_type_civil"
    const val APPLICANT_ORGANIZATION_TYPE_COMMUNAL = "applicant_organization_type_communal"
    const val APPLICANT_ORGANIZATION_TYPE_FARMER = "applicant_organization_type_farmer"
    const val APPLICANT_ORGANIZATION_TYPE_VICTIMS = "applicant_organization_type_victims"
    const val APPLICANT_ORGANIZATION_TYPE_HUMANS_RIGHT_WATCH = "applicant_organization_type_humans_right_watch"
    const val APPLICANT_ORGANIZATION_TYPE_OTHER = "applicant_organization_type_other"
    const val APPLICANT_ORGANIZATION_MEMBERSHIP_OTHER = "applicant_organization_membership_other"
    const val APPLICANT_ORGANIZATION_NAME = "applicant_organization_name"
    const val APPLICANT_ORGANIZATION_LEGAL_REPRESENTATIVE_STATUS_POSITIVE = "applicant_legal_representative_status_positive"
    const val APPLICANT_ORGANIZATION_LEGAL_REPRESENTATIVE_STATUS_NEGATIVE = "applicant_legal_representative_status_negative"
    const val APPLICANT_ORGANIZATION_LEGAL_REPRESENTATIVE_ID_NUMBER = "applicant_legal_representative_id_number"
    const val APPLICANT_PROVISIONAL_MEASURES_STATUS_POSITIVE = "applicant_provisional_measures_status_positive"
    const val APPLICANT_PROVISIONAL_MEASURES_STATUS_NEGATIVE = "applicant_provisional_measures_status_negative"
    const val APPLICANT_PROVISIONAL_MEASURES_TYPE_AMERICAN_COMMISSION = "applicant_provisional_measures_type_inter_american_commission"
    const val APPLICANT_PROVISIONAL_MEASURES_TYPE_AMERICAN_COURT = "applicant_provisional_measures_type_inter_american_court"
    const val APPLICANT_PROVISIONAL_MEASURES_TYPE_NATIONAL_JUDGE = "applicant_provisional_measures_type_national_judge"


    // BLOCK 6 RISK OR THREAT DATA
    const val RISK_OR_THREAT_REPORT = "risk_or_threat_report"

    // BLOCK 7 RISK SITUATION DATA
    const val RISK_SITUATION_TYPE_THREAT = "risk_situation_type_threat"
    const val RISK_SITUATION_TYPE_ATTACK = "risk_situation_type_attack"
    const val RISK_SITUATION_TYPE_KIDNAPPING = "risk_situation_type_kidnapping"
    const val RISK_SITUATION_TYPE_FAMILY_MEMBER_HOMICIDE = "risk_situation_type_family_member_homicide"
    const val RISK_SITUATION_TYPE_EXTORTION = "risk_situation_type_extortion"
    const val RISK_SITUATION_TYPE_RECRUITMENT = "risk_situation_type_recruitment"
    const val RISK_SITUATION_TYPE_OTHER = "risk_situation_type_other"
    const val RISK_SITUATION_OTHER_ACTUAL = "risk_situation_other_actual"
    const val RISK_SITUATION_MEANS_TYPE_BY_PHONE = "risk_situation_means_type_by_phone"
    const val RISK_SITUATION_MEANS_TYPE_VERBAL = "risk_situation_means_type_verbal"
    const val RISK_SITUATION_MEANS_TYPE_WRITTEN= "risk_situation_means_type_written"
    const val RISK_SITUATION_MEANS_TYPE_THROUGH_THIRD_PARTY = "risk_situation_means_type_through_third_party"
    const val RISK_SITUATION_MEANS_TYPE_SYMBOLIC = "risk_situation_means_type_symbolic"
    const val RISK_SITUATION_MEANS_TYPE_SOCIAL_MEDIA = "risk_situation_means_type_social_media"
    const val RISK_SITUATION_MEANS_TYPE_OTHER ="risk_situation_means_type_other"
    const val RISK_SITUATION_MEANS_OTHER_ACTUAL = "risk_situation_means_other"

    // BLOCK 8 POPULATION OBJECT OF PROTECTION
    const val PROTECTION_AND_PREVENTION_GROUP_1 = "protection_and_prevention_program_group_1"
    const val PROTECTION_AND_PREVENTION_GROUP_2 = "protection_and_prevention_program_group_2"
    const val PROTECTION_AND_PREVENTION_GROUP_3 = "protection_and_prevention_program_group_3"
    const val PROTECTION_AND_PREVENTION_GROUP_4 = "protection_and_prevention_program_group_4"
    const val PROTECTION_AND_PREVENTION_GROUP_5 = "protection_and_prevention_program_group_5"
    const val PROTECTION_AND_PREVENTION_GROUP_6 = "protection_and_prevention_program_group_6"
    const val PROTECTION_AND_PREVENTION_GROUP_7 = "protection_and_prevention_program_group_7"
    const val PROTECTION_AND_PREVENTION_GROUP_8 = "protection_and_prevention_program_group_8"
    const val PROTECTION_AND_PREVENTION_GROUP_9 = "protection_and_prevention_program_group_9"
    const val PROTECTION_AND_PREVENTION_GROUP_10 = "protection_and_prevention_program_group_10"
    const val PROTECTION_AND_PREVENTION_GROUP_11 = "protection_and_prevention_program_group_11"
    const val PROTECTION_AND_PREVENTION_GROUP_12 = "protection_and_prevention_program_group_12"
    const val PROTECTION_AND_PREVENTION_GROUP_13 = "protection_and_prevention_program_group_13"
    const val PROTECTION_AND_PREVENTION_GROUP_14 = "protection_and_prevention_program_group_14"
    const val PROTECTION_AND_PREVENTION_GROUP_15 = "protection_and_prevention_program_group_15"
    const val PROTECTION_AND_PREVENTION_GROUP_16 = "protection_and_prevention_program_group_16"
    const val PROTECTION_AND_PREVENTION_GROUP_17 = "protection_and_prevention_program_group_17"


    //BLOCK 9 PATRIOTIC UNION AND COMMUNIST PARTY SURVIVOR
    const val PATRIOTIC_UNION_AND_COMMUNIST_PARTY_SURVIVOR = "patriotic_union_and_communist_party_survivor"

    //BLOCK 10 ESPECIAL SECURITY AND PROTECTION GROUP
    const val ESPECIAL_SECURITY_AND_PROTECTION_GROUP = "especial_security_and_protection_group"
    const val ESPECIAL_SECURITY_AND_PROTECTION_GROUP_TYPE_LEADER = "especial_security_and_protection_group_type_leader"
    const val ESPECIAL_SECURITY_AND_PROTECTION_GROUP_TYPE_REPRESENTATIVE = "especial_security_and_protection_group_type_representative"
    const val ESPECIAL_SECURITY_AND_PROTECTION_GROUP_TYPE_MEMBER = "especial_security_and_protection_group_type_member"

    //BLOCK 13 CONSENT
    const val DATA_CONSENT_ACCEPTANCE = "data_consent_acceptance"
    const val NATIONAL_POLICE_PREVENTIVE_MEASURES_ACCEPTANCE_POSITIVE = "national_police_preventive_measures_acceptance_positive"
    const val NATIONAL_POLICE_PREVENTIVE_MEASURES_ACCEPTANCE_NEGATIVE = "national_police_preventive_measures_acceptance_negative"
    const val CERREM_WOMEN_ACCEPTANCE_POSITIVE = "cerrem_women_acceptance_positive"
    const val CERREM_WOMEN_ACCEPTANCE_NEGATIVE = "cerrem_women_acceptance_negative"
    const val APPLICANT_FULL_NAME = "applicant_full_name"
    const val APPLICANT_SIGNATURE = "applicant_signature"
    const val APPLICANT_FINGERPRINT = "applicant_fingerprint"

    //BLOCK 14 ENROLLER INFORMATION
    const val APPLICANT_IS_FORM_ENROLLER_POSITIVE = "applicant_is_form_enroller_positive"
    const val APPLICANT_IS_FORM_ENROLLER_NEGATIVE = "applicant_is_form_enroller_negative"
    const val FORM_ENROLLER_NAME_AND_LASTNAME = "form_enroller_name"
    const val ENROLLER_ENTITY_NAME = "enroller_entity_name"
    const val FORM_ENROLLER_PHONE_NUMBER = "form_enroller_phone_number"
    const val FORM_ENROLLER_EMAIL = "form_enroller_email"

    //BLOCK 15 PUBLIC SERVANT OR UNP FORM RECEIVER INFORMATION
    const val PUBLIC_SERVANT_OR_UNP_FORM_RECEIVER_NAME = "public_servant_or_unp_form_receiver_name"
    const val PUBLIC_SERVANT_OR_UNP_FORM_RECEIVER_EMAIL = "public_servant_or_unp_form_receiver_email"
    const val FILED_IN_IDENTIFIER = "filed_in_identifier"
}